baseURL = "/"
languageCode = "ja-jp"
languageLang = "ja"
isCJKLanguage = true
title = "滋賀情報Web"
timezone: Asia/Tokyo

pygmentsUseClasses = true
pygmentsCodefences = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[taxonomies]
  tag = "tags"
  category = "categories"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true