backend:
  name: git-gateway
  branch: main
media_folder: "/static/images/"
public_folder : "/static/images/"
locale: 'ja'


collections:
  - name: "News" 
    label: "News"
    folder: "content/news/"
    create: true
    path: "news/{{year}}/{{month}}/{{day}}{{hour}}{{minute}}"
    slug: "news/{{year}}/{{month}}/{{day}}{{hour}}{{minute}}"
    editor:
      preview: false #CMSの編集画面にプレビューがつく
    # コレクションのフィールド
    fields:
      - {label: "タイトル", name: "title", widget: "string"}
      - {label: "公開日", name: "date", widget: "datetime"}
      - {label: "タグ", name: "tags", widget: "list"}
      - {label: "あらすじ", name: "description", widget: "string", required: false}
      - {label: "Twitterカード", name: "card", widget: "select", options: ["summary", "summary_large_image"]}
      - {label: "PNG画像", name: "imgUrl", widget: "image", default: "/images/default.JPG"}
      - {label: "WebP画像", name: "imgUrlWebP", widget: "image", default: "/images/default.webp"}
      - {label: "画像出典表記", name: "imageBy", widget: "string", required: false}
      - {label: "本文", name: "body", widget: "text"}
